name: Cypress Tests

on:
  push:
    branches:
      - main # ajuste conforme o nome de sua branch principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Instalar dependências
        run: npm install

      - name: Instalar Cypress
        run: npm install cypress --save-dev

      - name: Executar testes do Cypress
        run: npm run cypress:run

